version: 2

aliases:
  - &restore-cache
    restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
  - &install-deps
    run:
        name: Install Dependencies
        command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
  - &build-packages
    run:
        name: Build
        command: yarn build
  - &save-cache
    save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn

jobs:
  build:
    working_directory: ~/nest
    docker:
      - image: cimg/node:16.17
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - *save-cache
      - run:
          name: Build
          command: yarn build    

  e2e_tests:
    working_directory: ~/nest
    docker:
      - image: cimg/node:16.17
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - run:
          name: E2E tests (graphql)
          command: yarn test:e2e:graphql
      - run:
          name: E2E tests (apollo)
          command: yarn test:e2e:apollo
      - run:
          name: E2E tests (mercurius)
          command: yarn test:e2e:mercurius
      - run:
          name: CLI Plugin & TypeScript <= v4.7 compatibility test 
          command: yarn add -D -W typescript@4.7.4 && cd packages/graphql && yarn test:e2e .visitor.spec.ts

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - e2e_tests:
          requires:
            - build
